name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install
      - name: Ensure mocha is executable
        run: chmod +x ./node_modules/.bin/mocha
      - run: npm start &
      - run: sleep 3
      - run: npm test
