name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # So Git can see all history

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          # Git config for pushing
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # Set remote with API key for auth
          CLEAN_API_KEY=$(echo "$HEROKU_API_KEY" | tr -d '\n')
          HEROKU_REMOTE="https://heroku:${CLEAN_API_KEY}@git.heroku.com/my-hw-app.git"
          git remote add heroku "$HEROKU_REMOTE" || git remote set-url heroku "$HEROKU_REMOTE"

          # Push to Heroku
          git push heroku main --force
